### ISSUE TITLE
Synching between mobile and desktop?

### ISSUE THREAD

**Issue by KennyDenvers** [dartungar/obsidian-mood-tracker#10]
I started using the Mood Tracker on mobile - after installing / enabling on desktop I cannot view my previous (mobile) entries. What do I need to do?

**Comment by dartungar** [comment]
@KennyDenvers hey! The data is stored in .json file. To ensure it's synced you should make sure that:
- you have some kind of sync in the first place
- if you are using Obsidian Sync, make sure data folder is not in excluded folders, and 'Sync all other types' option is enabled.

**Comment by KennyDenvers** [comment]
yes, thank you! "sync all other types" did the trick!
