### ISSUE TITLE
"Bored" mood option

### ISSUE THREAD

**Issue by evhanlabrie** [dartungar/obsidian-mood-tracker#15]
Would it be possible to add a "Bored" mood? Also, it may be a good idea to open an issue where people can suggest moods.

Another thing, is it possible, in a daily note, to link only to that day's mood history?

Thanks!

**Comment by dartungar** [comment]
@evhanlabrie hey there! I've added some default emotions (https://github.com/dartungar/obsidian-mood-tracker/releases/tag/0.2.2), but you can always add them yourself via settings!

As for the linking to daily notes - I'm going to add an option to add moods directly to the daily notes some time soon.
