### ISSUE TITLE
Mood tracker timestamps do not follow timezones

### ISSUE THREAD

**Issue by evhanlabrie** [dartungar/obsidian-mood-tracker#17]
Sorry if the title is a but confusing.

To put it simply, data saved in the JSON is based on the UTC timezone instead of the device time. For example, I'm in the UTC-4, and every timestamp is 4 hours ahead.

They seem to be converted in the app itself, but when I filter based on a date, every day is shifted by 4 hours. So if I filter for 2023-07-22, I'll get every entry from 2023-07-11 20:00 to 2023-07-22 20:00.

Thank you!

**Comment by dartungar** [comment]
@evhanlabrie should be fixed in 0.2.3. 
Jeez, dates in JS are crazy 🤡
