### ISSUE TITLE
Editing

### ISSUE THREAD

**Issue by konstantin83** [dartungar/obsidian-mood-tracker#19]
Hi! Thanks for a wonderful idea for a plugin. I think it's really useful.

Can you tell me how to edit previously entered data? I am translating tags to another language, but recently selected/entered data is not changable. I guess I can edit everything in the json file, but is there any more UX friendly way?

**Comment by dartungar** [comment]
@konstantin83 it's on the roadmap! https://github.com/dartungar/obsidian-mood-tracker#roadmap

**Comment by dartungar** [comment]
@konstantin83 implemented in 1.0.0.
