### ISSUE TITLE
FR: reminder

### ISSUE THREAD

**Issue by huachuman** [dartungar/obsidian-mood-tracker#24]
I it possible to get this to remind the user to rate their mood on a regular basis? 

This type of thing typically gets forgotten after a short while.

Without a reminder to note your mood, this will suffer from feature blindness/forgetfulness.

This is a concept I never see anyone talking about so here's a quick overview:

> It refers to when users don't know a feature exists or forget about it because the user interface doesn't make it clear or visible. Out of sight, out of mind.
> 
> It's closely related to the concept of discoverability - how easy it is for users to find and figure out features in software. Low discoverability leads to more feature blindness.
> 
> It can happen either because the feature is buried in complex menus where users won't find it, or because there are no visual cues (like buttons) to trigger awareness and memory of the feature.
> 
> It leads to software capabilities being unused and value left on the table. The features are there but never utilized.
> 
> Common solutions involve surface-level design changes to make features more visible, findable, self-explanatory, and easier to interact with. This reduces the out-of-sight effect.

**Comment by dartungar** [comment]
@huachuman it is possible, however it is certainly out of scope of this plugin.
Here's what you can do:
- put a point in daily checklist to track your mood (that's what I do; my checklist is in my daily note with my tasks, so I get to see it very often)
- put a reminder on your phone/PC
- add it to habit tracker of choice
- use https://github.com/uphy/obsidian-reminder - however I personally find reminders inside Obsidian quite useless.

Hope some of this helps. Cheers! Closing the issue now.
