### ISSUE TITLE
Embeddable graph for notes

### ISSUE THREAD

**Issue by winged-voices** [dartungar/obsidian-mood-tracker#36]
Is there a way to embed the graph in an entry? That would be great for monthly notes, or dashboards.

**Comment by dartungar** [comment]
@winged-voices that'd be cool, but not trivial for me to implement. Will add it to backlog though!

**Comment by dartungar** [comment]
@winged-voices implemented in 1.2.0.

**Comment by winged-voices** [comment]
That's so awesome, thank you so much!!
