### ISSUE TITLE
emoji missing in tracker graph

### ISSUE THREAD

**Issue by sojohnnysaid** [dartungar/obsidian-mood-tracker#39]
One of the emojis for some reason does not load on the y axis

<img width="542" alt="image" src="https://github.com/dartungar/obsidian-mood-tracker/assets/16521766/61df0956-2f27-4c4c-9227-ab6a8105334f">

**Comment by dartungar** [comment]
@sojohnnysaid hey there! emojis are just text, like letters. if it does not display property it probably has to do with your OS fonts, or Obsidian. some emojis do not display for me, too! nothing I can do about that.
