### ISSUE TITLE
a bug on momentjs

### ISSUE THREAD

**Issue by iczrac** [dartungar/obsidian-mood-tracker#47]
Hi, this really a awesome plugin！

I used this path {{DATE:YYYY/[M]MM/[W]ww/YYYY-MM-DD_ddd}} for my daily notes，and I found it good to translate “YYYY/[M]MM/[W]ww/YYYY-MM-DD” but expect "ddd}".

Hope you can fix it soon!

**Comment by dartungar** [comment]
@iczrac should be fixed in v1.3.3. Please check and see if it's working now!
