### ISSUE TITLE
Ability to pick where template goes in file

### ISSUE THREAD

**Issue by angiioh** [dartungar/obsidian-mood-tracker#50]
Hi! Been enjoying using your plugin. I was wondering if there is a way to pick where the template will insert into my daily note. For example, I'd like it to always be on line 6 for consistency between entries. I'm new to Obsidian, so I wasn't sure if there was something I could do on my end for that, but if not, consider this a feature request. :]

Thank you!

**Comment by dartungar** [comment]
@angiioh hey there! It's definitely on the list, but I can't give any ETA :)

**Comment by angiioh** [comment]
Awesome, no worries. I'm essentially trying to recreate my livejournal from 20 years ago with the mood picker, so it's not exactly a pressing matter, haha. Thanks!
